### ISSUE TITLE
Gallery only showing one image and is not editable

### ISSUE THREAD

**Issue by basti2305** [VanOns/laraberg#120]
When adding a gallery block I can select multiple images from the laravel filemanager. In the editor only the first image is shown.
Also the gallery is not editable so it has to be deleted and created again.

**Comment by markxxv** [comment]
Same problem

**Comment by apaliray03** [comment]
@mauricewijnia Users are having problems selecting multiple images for gallery, and it's been causing some inconveniences for them. The problem is that the editor shows only the first photo that's been selected. Is there a way to fix this?

**Comment by mikebronner** [comment]
Since it's been a while, I wanted to bump this issue, as I am having this problem as well. @basti2305 @markxxv have you been able to find a solution yet?

**Comment by deimozz** [comment]
Apperently, this is mostly an issue with Gutenberg.

I basically rebuilt laraberg.js with v8.2.0 as the base instead of v8.1.0 and it KINDA works with some caveats:

1. Using multiselect from the file manager does NOTHING. Only the first selection works
2. The Upload button, of course, does not work. 
3. You can add more pictures into the gallery by simply clicking on Media Library and then selecting your desired photo. For some reason, this does not work on the first click, but the other clicks, all good !

**Comment by kayastha1988** [comment]
Is there any possibility to hide/remove Gallery icon from editor since its not worth it to implement??? How I can remove that icon from editor?

Thanks in advance.

**Comment by estudiooka** [comment]
+1

**Comment by estudiooka** [comment]
> Is there any possibility to hide/remove Gallery icon from editor since its not worth it to implement??? How I can remove that icon from editor?
> 
> Thanks in advance.

 window.wp.blocks.unregisterBlockType('core/gallery')

**Comment by Grozerg** [comment]
Hi guys, I also faced these problems:
1. Gallery only showing one image
2. Gallery is not editable 

The first error was fixed, for this in 737 line \vendor\unisharp\laravel-filemanager\public\js\script.js https://i.imgur.com/jVl0YuJ.png

 ```
 // replace from  
  window.opener.SetUrl(getSelectedItems());
  
  // to 
  getSelectedItems().forEach(function(item) {
      window.opener.SetUrl([item]);
  });
```

For some reason, window.opener.SetUrl only passes the first element of the array (first chosed image)

Any ideas for the second error?
