### ISSUE TITLE
Reusable Block Not Working Properly!

### ISSUE THREAD

**Issue by chiragsenjaliya** [VanOns/laraberg#133]
**Describe the bug**
I can't get a reusable block on a new page. If I create a reusable block then it will show on edit but not on create a page!

also, I am getting this on editor load

_Uncaught (in promise) []
Uncaught (in promise) []_

**Comment by mauricewijnia** [comment]
Hi!

You left out a lot of information that the bug report template asks for. Could you add the version number you're having this problem with?

**Comment by chiragsenjaliya** [comment]
I am using laraberg 1.1.1

**Comment by mauricewijnia** [comment]
Okay, this will most likely be fixed in an upcoming v2.0.0 release!

**Comment by chiragsenjaliya** [comment]
Hey @mauricewijnia thank you for the quick reply. I am eagerly waiting for a new update. Thanks!

**Comment by chiragsenjaliya** [comment]
@mauricewijnia  can you tell me when will version 2.0 will release?

**Comment by chiragsenjaliya** [comment]
@mauricewijnia any update on version 2.0? Looking forward to it!

**Comment by dkruchok** [comment]
This issue comes from _api-fetch_ function and you can catch it in **gutenberg/packages/api-fetch/src/index.js:138**
In my case it complaints about **users** and **taxonomy** mock.
But I do not have enough experience with React to fix this...
Your built version does not have this issue but if I rebuild the source it appears...
Reusable blocks do not appear because of this....

@mauricewijnia maybe you have any advice on how this can be fixed, that would be really helpful

Laraberg 1.1.1
Gutenberg 8.1.0
NPM 6.14.4
Node v14.17.4
