### ISSUE TITLE
Add table doesn't work

### ISSUE THREAD

**Issue by Basdl76** [VanOns/laraberg#53]
Adding/creating table doesn't work
When i select table and click on create table nothing happened. Also no console error. 
Hope you can fix it :))

version: "van-ons/laraberg": "^1.0",

![image](https://user-images.githubusercontent.com/53794175/64116689-4c917b00-cd93-11e9-9c11-7abd819abcf2.png)

![image](https://user-images.githubusercontent.com/53794175/64116645-32579d00-cd93-11e9-8489-b486423e0179.png)

**Comment by kapitoxapux** [comment]
> The problem seems to be that, for whatever reason, the `Create Table` button has the type set to `button` rather than `submit`, and the Table form is looking for that submit event.

Changing type="button" to type="submit" fixed that

**Comment by mauricewijnia** [comment]
This is indeed because the button type is 'button'.
The problem is that Gutenberg leaves a lot of button types empty, this causes a lot of buttons to submit the form that Laraberg is in because the default button type is 'submit'.

I'll be looking into this today, hopefully I can come up with a fix that gets around this issue and any similar issues entirely, if not I'll add this button to the 'whitelist' of submit buttons.
