### ISSUE TITLE
Image block broken if saved with out selected image 

### ISSUE THREAD

**Issue by captnCC** [VanOns/laraberg#54]
**Describe the bug**
If an image block without selected image is saved, the next time the editor is opened the block will be broken and unusable and even new image blocks will be unuseable.

![Screenshot 2019-09-08 at 20 58 15](https://user-images.githubusercontent.com/5840945/64493049-6e02d300-d27b-11e9-8e97-d45618367fb8.png)
![Screenshot 2019-09-08 at 21 01 40](https://user-images.githubusercontent.com/5840945/64493089-e8cbee00-d27b-11e9-9e96-1facb0e7aabd.png)

While looking in the causing lines of code, it seem like Gutenberg tries to load the default wp media library

**To Reproduce**
Reproduce able in the demo 
1. Create Image block without image
2. Save content 
3. Open editor

**Expected behavior**
The block should display the default empty state

**Environment (please complete the following information):**
- Laraberg Version: 1.0.1
 - OS: macOS
 - Browser: Chrome, Safari

**Comment by mauricewijnia** [comment]
I have looked into this but haven't found a solution yet.
It looks like the `window.wp` object is undefined when trying to load an empty image block.
I tried some dirty fixes in the Gutenberg code, but that didn't accomplish anything, I'll have to look into this when I have some more time...

**Comment by captnCC** [comment]
I am using the Drupal Gutenberg Module in another project and found that it works there in the correct way. May be you can find the fix in their code 

[Drupal Gutenberg Repo](https://git.drupalcode.org/project/gutenberg)

**Comment by mauricewijnia** [comment]
Haha thanks! I did look into their code, but sadly I couldn't find out what difference causes this issue.

**Comment by mauricewijnia** [comment]
Spent some time trying to figure this issue out again, but came up with nothing.
For some reason something regarding media/images crashes in Gutenberg when an image has no `src` attribute.

In order to prevent the image blocks from crashing entirely when this happens, I've implemented a (hacky) fix that add's a `src` pointing to a placeholder image to any images that have no `src` attribute. This atleast prevents the image blocks from becoming unusable.
