### ISSUE TITLE
Embed blocks broken

### ISSUE THREAD

**Issue by FlusherDock1** [VanOns/laraberg#66]
**Describe the bug**
If you try to use embed block it won't work.

**To Reproduce**
1. Go to http://demo.laraberg.io/articles/create
2. Add any new embed block
3. Paste link and click embed
4. Button does nothing

**Expected behavior**
Standart embed block behavior

**Screenshots**
![Снимок экрана 2019-11-06 в 16 24 52](https://user-images.githubusercontent.com/20070837/68301894-f81bbc00-00b1-11ea-95d3-5a2bed00f405.png)

**Environment (please complete the following information):**
- Laraberg Version: version of http://demo.laraberg.io/
 - Browser Chrome
 - Version 78

**Comment by lhilton** [comment]
Confirming that I reproduce this same issue

**Comment by lhilton** [comment]
@FlusherDock1 (or anyone else landing here), I ended up finding this solution that I experimentally just put in a blade view to test:

```php
        <div class="gutenberg__content wp-embed-responsive">
            {!! VanOns\Laraberg\Helpers\BlockHelper::renderBlocks(
                    VanOns\Laraberg\Helpers\EmbedHelper::renderEmbeds( $page['data']['contents']['content'] )
                )
            !!}
        </div>
```

I am using the BlockHelper and the EmbedHelper directly here, since this is effectively what the Block model is doing when you render content out.. This allows my video embeds to work correctly, along with the other content I have looked at.

**Comment by FlusherDock1** [comment]
Fixed in new release
